config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  constraints(host: "whygitisbetterthanx.com") do
    root to: "site#redirect_wgibtx", as: :whygitisbetterthanx
  end

  constraints(host: "progit.org") do
    root to: "site#redirect_book", as: :progit
    get "*path" => "site#redirect_book"
  end

  get "site/index"

  scope :doc, as: :doc do
    get "/"    => "doc#index"
    get "/ext" => "doc#ext"
    get "/credential-helpers" => "doc#credential_helpers"
  end

  scope :docs, as: :docs do
    get "/" => "doc#ref"
  end

  scope :docs do
    get "/howto/:file", to: redirect { |path_params, _req|
      "https://github.com/git/git/blob/master/Documentation/howto/#{path_params[:file]}.txt"
    }

    get "/:file.html" => "doc#man", :as => :doc_file_html, :file => /[\w\-.]+/
    get "/:file"      => "doc#man", :as => :doc_file,      :file => /[\w\-.]+/

    get "/:file/:version" => "doc#man", :version => /[^\/]+/
  end

  %w[man ref git].each do |path|
    get "/#{path}/:file" => redirect("/docs/%<file>s")
    get "/#{path}/:file/:version" => redirect("/docs/%<file>s/%<version>s"), :version => /[^\/]+/
  end

  resource :book do
    get "/ch:chapter-:section.html"       => "books#chapter"
    get "/:lang/ch:chapter-:section.html" => "books#chapter"

    get "/index"    => redirect("/book")
    get "/commands" => redirect("/docs")

    nested do
      scope ":lang" do
        get "/v1"                => redirect("/book/%<lang>s/v2")
        get "/v1/:slug"          => redirect("/book/%<lang>s/v2/%<slug>s")
        get "/v1/:chapter/:link" => redirect("/book/%<lang>s/v2/%<chapter>s/%<link>s")

        get "/v:edition"                => "books#show"
        get "/v:edition/:slug"          => "books#section"
        get "/v:edition/:chapter/:link" => "books#link", :chapter => /(ch|app)\d+/

        get "/"      => "books#show",    :as => :lang
        get "/:slug" => "books#section", :as => :slug
      end
    end
  end

  scope :download, as: :download do
    get "/"              => "downloads#index"
    get "/:platform"     => "downloads#download"
    get "/gui/:platform" => "downloads#gui"
  end

  resources :downloads, only: [:index] do
    collection do
      get "/guis"       => "downloads#guis"
      get "/installers" => "downloads#installers"
      get "/logos"      => "downloads#logos"
      get "/latest"     => "downloads#latest"
    end
  end

  get "/blog" => "blog#index"
  get "/blog/*post" => redirect("/blog")
  get "/:year/:month/:day/:slug" => redirect("/blog"), :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/

  get "/about"          => "about#index"
  get "/about/:section" => "about#index"

  get "/videos"    => "doc#videos"
  get "/video/:id" => "doc#watch"

  get "/community" => "community#index"

  get "/search"         => "site#search"
  get "/search/results" => "site#search_results"

  # historical synonyms
  namespace :documentation do
    get "/"                     => redirect("/doc")
    get "/reference"            => redirect("/docs")
    get "/reference/:file.html" => redirect { |path_params, _req| "/docs/#{path_params[:file]}" }
    get "/book"                 => redirect("/book")
    get "/videos"               => redirect("/videos")
    get "/external-links"       => redirect("doc/ext")
  end

  get "/sfc"        => "site#sfc"
  get "/site"       => "site#about"
  get "/trademark"  => redirect("/about/trademark")

  get "/contributors" => redirect("https://github.com/git/git/graphs/contributors")

  root to: "site#index"
end

app/controllers/site_controller.rb
# frozen_string_literal: true

class SiteController < ApplicationController
  def index
    expires_in 10.minutes, public: true

    @section    = "home"
    @subsection = ""
  end

  # called when you start typing into search form
  def search
    @term = sname = request.query_parameters["search"].to_s.downcase
    @data = search_term(sname)
    render partial: "shared/search"
  end

  # called when you submit your search
  def search_results
    @term = sname = request.query_parameters["search"].to_s.downcase
    data = search_term(sname)
    @top = []
    @rest = []
    data[:results].each do |type|
      type[:matches].each do |hit|
        if hit[:score] >= 1.0
          @top << hit
        else
          @rest << hit
        end
      end
    end
    @top.sort! { |a, b| b[:score] <=> a[:score] }
    @rest.sort! { |a, b| b[:score] <=> a[:score] }
    render "site/results"
  end

  def search_term(sname)
    data = {
      term: sname,
      results: []
    }

    if (results = Doc.search(sname))
      data[:results] << results
    end

    if (results = Section.search(sname, lang: "en"))
      data[:results] << results
    end

    data
  end

  def redirect_wgibtx
    redirect_to "https://git-scm.com/about"
  end

  def redirect_book
    current_uri = request.env["PATH_INFO"]
    if current_uri == "/"
      redirect_to "https://git-scm.com/book"
    else
      redirect_to "https://git-scm.com#{current_uri}"
    end
  end
end

app/helpers/site_helper.rb
# frozen_string_literal: true

module SiteHelper
  def highlight_no_html(high)
    strip_tags(high.to_s)
      .gsub("[highlight]", '<span class="highlight">')
      .gsub("[xhighlight]", "</span>")
  end
end

app/views/site/about.html.erb
<div id="main">
  <h1>About git-scm.com</h1>

  This site is open source and maintained by members of the Git
  community.  We welcome patches, suggestions, and corrections.

  <h2>Open Source</h2>

  The content on this site is pulled from multiple sources. It is
  available under various licenses, and bugs reports should be directed
  to the appropriate repositories:

  <ul>

    <li>Most of the "base" site content is hosted in the
    <a href="https://github.com/git/git-scm.com">git/git-scm.com</a>
    repository at GitHub. That includes all pages except the book and
    manpages, along with the general design of the site. This content
    is available under the
    <a href="https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt">MIT license</a>.
    Bug reports and suggestions may be made in that repository.

    <li>Content from the ProGit book is imported from the
    <a href="https://github.com/progit/progit2">progit/progit2</a>
    repository, which is available under a Creative Commons
    <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/">CC-BY-NC-SA</a>
    license, <a href="https://github.com/progit/progit2/blob/master/LICENSE.asc">
    as specified in the progit2 repository</a>. Bug reports and
    suggestions on the technical content or English language version of
    the book should be made in the progit2 repository. Fixes for
    translated versions of the book should be made in the
    <a href="https://github.com/progit/progit2/blob/master/TRANSLATING.md#helping-with-a-existing-project">
    appropriate language-specific repository</a>.


    <li>The reference manual is imported from the Git project, and is
    available under the <a href="https://github.com/git/git/blob/master/COPYING">GPL</a>.
    Bug reports and suggestions should be made to the upstream
    <a href="/community">Git community</a>.

    <li>Bugs in the Git software itself should similarly go to the
    <a href="/community">Git community</a>.

  </ul>

  <h2>Authors</h2>

  <p>This site was originally conceived and written by
  <a href="https://github.com/schacon">Scott Chacon</a>.
  Much of the current visual design is the work of
  <a href="https://github.com/jasonlong">Jason Long</a>.
  The site is currently collaboratively maintained in the
  <a href="https://github.com/git/git-scm.com">git-scm.com</a>
  repository at GitHub.

  <p>Credit also goes to the many contributors, bug reporters, and
  maintainers over the years, both in this repository and in others from
  which we pull content. See the individual repository histories for a
  complete list.

  <h2>Sponsors</h2>

  We are grateful to the companies which have donated resources and
  services to keep the site running, including:

  <ul>
    <li>
      <a href="https://fusionauth.io">FusionAuth</a>, whose annual
      donation to the Git project pays for the hosting costs of this
      website.
    </li>
    <li><a href="https://cloudflare.com">Cloudflare</a>
    <li><a href="https://bonsai.io/">Bonsai</a>
  </ul>

  For a detailed view of the site's network layout, see our
  <a href="https://github.com/git/git-scm.com/blob/main/ARCHITECTURE.md">architecture document</a>.

</div>

app/views/site/index.html.erb
<div id="front-content">
  <section id="front-navigation">
    <nav id="front-nav">
      <ul>
        <li id="nav-about">
          <%= link_to about_path do %>
            <img src="/images/icons/nav-about@2x.png" width="74" height="74" />
            <h3>About</h3>
            <p>The advantages of Git compared to other source control systems.</p>
          <% end %>
        </li>
        <li id="nav-documentation">
          <%= link_to doc_path do %>
            <img src="/images/icons/nav-documentation@2x.png" width="74" height="74" />
            <h3>Documentation</h3>
            <p>Command reference pages, Pro Git book content, videos and other material.</p>
          <% end %>
        </li>
        <li id="nav-downloads">
          <%= link_to downloads_path do %>
            <img src="/images/icons/nav-downloads@2x.png" width="74" height="74" />
            <h3>Downloads</h3>
            <p>GUI clients and binary releases for all major platforms.</p>
          <% end %>
        </li>
        <li id="nav-community">
          <%= link_to community_path do %>
            <img src="/images/icons/nav-community@2x.png" width="74" height="74" />
            <h3>Community</h3>
            <p>Get involved! Bug reporting, mailing list, chat, development and more.</p>
          <% end %>
        </li>
      </ul>
    </nav>
    <div id="front-book">
      <img src="/images/progit2.png" width="56" height="74" />
      <p>
        <strong><a href="/book">Pro Git</a></strong>
        by Scott Chacon and Ben Straub is available to
        <a href="/book">read online for free</a>.
        Dead tree versions are available on <a href="https://www.amazon.com/Pro-Git-Scott-Chacon/dp/1484200772?ie=UTF8&camp=1789&creative=9325&creativeASIN=1430218339&linkCode=as2&tag=git-sfconservancy-20">Amazon.com</a>.
      </p>
    </div>
  </section>
  <section id="front-downloads">
    <%= render partial: 'shared/monitor' %>
    <table>
      <tr>
        <td nowrap="true"><%= link_to "Graphical UIs", "/downloads/guis", class: 'icon gui', id: 'gui-link' %></td>
        <td nowrap="true"><%= link_to "Tarballs", "https://www.kernel.org/pub/software/scm/git/", class: 'icon older-releases' %></td>
      </tr>
      <tr>
        <td nowrap="true"><%= link_to "Windows Build", "/download/win", class: 'icon windows', id: 'alt-link' %></td>
        <td nowrap="true"><%= link_to "Source Code", "https://github.com/git/git", class: 'icon source' %></td>
      </tr>
    </table>
</section>
</div>

<section id="companies-projects">
  <h3 class="text-center"> Companies &amp; Projects Using Git </h3>
  <ul>
    <li><%= link_to "Google", "https://github.com/google", class: 'google' %></li>
    <li><%= link_to "Microsoft", "https://github.com/Microsoft", class: 'microsoft' %></li>
    <li><%= link_to "Twitter", "https://github.com/twitter", class: 'twitter' %></li>
    <li><%= link_to "LinkedIn", "https://github.com/linkedin", class: 'linked-in' %></li>
    <li><%= link_to "Netflix", "https://github.com/netflix", class: 'netflix' %></li>
    <li><%= link_to "Perl", "https://perl5.git.perl.org/perl.git", class: 'perl' %></li>
    <li><%= link_to "PostgreSQL", "https://git.postgresql.org/gitweb/", class: 'postgresql' %></li>

    <li><%= link_to "Android", "https://android-review.googlesource.com/#/q/status:open,n,z", class: 'android' %></li>
    <li><%= link_to "Linux", "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git", class: 'linux' %></li>
    <li><%= link_to "Ruby on Rails", "https://github.com/rails/rails", class: 'rails' %></li>
    <li><%= link_to "Qt", "https://code.qt.io/cgit/", class: 'qt' %></li>
    <li><%= link_to "Gnome", "https://gitlab.gnome.org/GNOME", class: 'gnome' %></li>
    <li><%= link_to "Eclipse", "https://git.eclipse.org/c/", class: 'eclipse' %></li>
    <li><%= link_to "KDE", "https://invent.kde.org/explore/groups", class: 'kde' %></li>
    <li><%= link_to "X", "https://cgit.freedesktop.org/xorg/xserver/", class: 'x' %></li>
</ul>
</section>

app/views/site/results.html.erb
<% @section = "search" %>
<% @subsection = "" %>
<% @page_title = "Search results for #{h(@term)}" %>

<div id="main">
  
  <h1><%= raw "Search results for <strong>#{h(@term)}</strong>" %></h1>
  
  <% if @top.size > 0 %>
    <div class="callout top-matches">
      <ol class="full-search-results">
        <% @top.each do |hit| %> 
          <li>
            <h3><%= link_to hit[:name], hit[:url] %></h3>
            <%= link_to hit[:url], hit[:url], class: 'url' %>
            <p><%= raw highlight_no_html(hit[:highlight]) %></p>
          </li>
        <% end %>
      </ol>
    </div>
  <% end # @top.size > 0 %>

  <% if @rest.size > 0 %>
    <ol class="full-search-results">
      <% @rest.each do |hit| %>
        <li>
          <span class="relevancy">
            <% total = (hit[:score] * 10).ceil %>
            <% rest  = 10 - total %>
            <% rest.times do %>
              <img src="/images/icons/grey-dot.png" alt="">
            <% end %>
            <% total.times do %>
              <img src="/images/icons/green-dot.png" alt="">
            <% end %>
          </span>
          <h3>
            <%= link_to hit[:name], hit[:url] %>
          </h3>
          <%= link_to hit[:url], hit[:url], class: 'url' %>
          <p>
            <%= raw highlight_no_html(hit[:highlight]) %>
          </p>
        </li>
      <% end %>
    </ol>
  <% end %>
  
  <% if @rest.size + @top.size == 0 %>
    <h2> Sorry, no search matches </h2>
  <% end %>
</div>

app/views/site/sfc.html.erb
<div id="main">
  <h1 id="sfc">Git and Software Freedom Conservancy</h1>

  <p>Git is a member project of <a href="https://sfconservancy.org/">Software
  Freedom Conservancy</a>.  Conservancy is a not-for-profit organization that
  provides financial and administrative assistance to open source projects.

  <h2 class="section-start">Donation</h2>

  <p>Conservancy accepts donations on git's behalf. In the past, project money has
  typically gone to defraying travel costs for developers to come to our annual
  <a href="https://git.wiki.kernel.org/index.php/GitTogether">GitTogether</a>
  mini-conference.  A portion of the money goes to Conservancy to cover their
  operating expenses. You can also donate <a
  href="https://sfconservancy.org/donate">directly</a> to Software
  Freedom Conservancy's general fund.

  <h3 class="title">Paypal</h3>
  <p>To donate to Git via PayPal:
  <div class="center">
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="GXTE9AECX4LAL">
      <input type="image"
             src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif"
             border="0" name="submit"
             alt="PayPal - The safer, easier way to pay online!">
      <img alt="" border="0" height="1" width="1"
           src="https://www.paypal.com/en_US/i/scr/pixel.gif">
    </form>
  </div>

  <h3 class="title">Check</h3>
  <p>We can also accept donations drawn in USD from banks in the USA
  (donations from banks outside of the US or not in USD should be handled
  by wire). Make checks payable to "Software Freedom Conservancy, Inc."
  and place "Directed donation: Git" in the memo field. Checks should be
  mailed to:
  <div class="center">
  <pre>
  Software Freedom Conservancy, Inc.
  137 Montague ST STE 380
  BROOKLYN, NY 11201 USA
  </pre>
  </div>

  <h3 class="title">Wire</h3>
  <p>Conservancy can accept wire donations, but the instructions vary
  depending on the country of origin. Please contact <a
    href="mailto:accounting@sfconservancy.org">accounting@sfconservancy.org</a>
  for instructions.

  <h3 class="title">Stock</h3>
  <p>Conservancy also accepts stock donations on behalf of the Git
  project. If you would like to donate stock, please contact <a
    href="mailto:accounting@sfconservancy.org">accounting@sfconservancy.org</a>
  for instructions on how to initiate the transfer.

</div>